### ISSUE TITLE
Crear pdf con el esquemático

### ISSUE THREAD

**Issue by ggavinowich** [fiuba-labo-de-micro-miercoles/2016_1c_trabajo_practico-solar_tracker#1]
Hola, buenísimo que hayan subido el esquemático. ¿Pueden por favor subir una versión en pdf para que podamos verla sin tener que instalar el Kicad?

**Comment by Mecanigio** [comment]
Perdon, recien lo veo! ahi subi el esquemático en pdf.

Saludos!

Equipo Solar Tracker.
