### ISSUE TITLE
¿Parte de mecánica?

### ISSUE THREAD

**Issue by fbaglivo** [fiuba-labo-de-micro-miercoles/2016_1c_trabajo_practico-solar_tracker#2]
Estimados, buenísimo que mantengan actualizado el repo. 

Les quería preguntar si uds ya tienen resuelta la parte mecánica (como montar el panel, si van a hacer algo a escala y van a usar un panel chico, etc).

**Comment by GedSid** [comment]
Estamos en eso, tenemos un par de cosas resueltas y un par más por
resolver. Durante esta semana esperamos resolverlo, para la semana que
viene inprimir los engranajes.
La idea es no hacer una maqueta, sino el aparato definitivo.

Saludos,
Joaquín Ulloa
